---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/services

- Zoo:
    - Portainer:
        href: https://localhost:9443/#
        description: Portainer

- My Second Group:
    - My Second Service:
        href: http://localhost/
        description: Homepage is the best

- My Third Group:
    - My Third Service:
        href: http://localhost/
        description: Homepage is 😎
