name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Make all the scripts executable
      run: # MAKE ALL SHELL SCRIPTS IN THE CURRENT DIRECTORY EXECUTABLE
          chmod +x *.sh
    - name: Change into postgres-pgadmin directory
      run: # CHANGE INTO THE POSTGRES-PGADMIN4 DIRECTORY
          cd postgres-pgadmin && ls -la
    - name: Show current directory
      run: pwd && ls -la
      shell: bash
    - name: Running the postgres & pgadmin scripts
      run: # RUN POSTGRES SCRIPTS IN THE CURRENT DIRECTORY
          ./postgres.sh
    - name: Stop all running containers
      run:
          ./stop.sh
