name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Show current directory
      run: pwd && ls -la
      shell: bash
    - name: Make all the scripts executable
      run: # MAKE ALL SHELL SCRIPTS IN THE CURRENT DIRECTORY EXECUTABLE
          chmod +x *.sh
      shell: bash\
    - name: Cd into the postgres directory
      run: # CD INTO THE POSTGRES DIRECTORY
          cd postgres-pgadmin
      shell: bash
    - name: Running the postgres Scripts
      run: # RUN POSTGRES SCRIPTS IN THE CURRENT DIRECTORY
          ./postgres.sh
      shell: bash
    - name: Stop all running containers
      run:
          ./stop.sh
      shell: bash
