name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Running the Scripts
      run: # RUN ALL SHELL SCRIPTS IN THE CURRENT DIRECTORY
          echo "Running all shell scripts in the current directory:"
          find $DIR -type f -name "*.sh" -exec basename {} \; -exec sh {} \;

