name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Cd folder
      run: cd mongo-compass-docker


    - name: Install dependencies
      run: make

    - name: Run check
      run: make check

    - name: Run build
      run: make build
      
